from building import *

cwd     = GetCurrentDir()
src	= Glob('*.c')+ Glob('*.cpp') + Glob('*_gcc.S')

group = DefineGroup('Applications', src, depend = [''])

objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = group + objs

Return('group')


Return('group')
